# Generated by Django 2.1.15 on 2023-06-13 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wagazistore', '0003_auto_20230613_1259'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('name', models.CharField(max_length=100)),
                ('message', models.TextField()),
            ],
        ),
    ]
